# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'citizen_pac.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CitizenPacMainWindow(object):
    def setupUi(self, CitizenPacMainWindow):
        CitizenPacMainWindow.setObjectName(_fromUtf8("CitizenPacMainWindow"))
        CitizenPacMainWindow.setEnabled(True)
        CitizenPacMainWindow.resize(800, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CitizenPacMainWindow.sizePolicy().hasHeightForWidth())
        CitizenPacMainWindow.setSizePolicy(sizePolicy)
        CitizenPacMainWindow.setMinimumSize(QtCore.QSize(800, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/view/qt_configs/images/logo_36x36.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CitizenPacMainWindow.setWindowIcon(icon)
        self.citizenCentralWidget = QtGui.QWidget(CitizenPacMainWindow)
        self.citizenCentralWidget.setEnabled(True)
        self.citizenCentralWidget.setMinimumSize(QtCore.QSize(800, 800))
        self.citizenCentralWidget.setObjectName(_fromUtf8("citizenCentralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.citizenCentralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.statsBarContainerWidget = QtGui.QWidget(self.citizenCentralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsBarContainerWidget.sizePolicy().hasHeightForWidth())
        self.statsBarContainerWidget.setSizePolicy(sizePolicy)
        self.statsBarContainerWidget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.statsBarContainerWidget.setObjectName(_fromUtf8("statsBarContainerWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.statsBarContainerWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.statsBarCheckBox = QtGui.QCheckBox(self.statsBarContainerWidget)
        self.statsBarCheckBox.setEnabled(True)
        self.statsBarCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.statsBarCheckBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.statsBarCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.statsBarCheckBox.setText(_fromUtf8(""))
        self.statsBarCheckBox.setObjectName(_fromUtf8("statsBarCheckBox"))
        self.horizontalLayout.addWidget(self.statsBarCheckBox)
        spacerItem = QtGui.QSpacerItem(3, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.statsBarCheckBoxLabel = QtGui.QLabel(self.statsBarContainerWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsBarCheckBoxLabel.sizePolicy().hasHeightForWidth())
        self.statsBarCheckBoxLabel.setSizePolicy(sizePolicy)
        self.statsBarCheckBoxLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.statsBarCheckBoxLabel.setObjectName(_fromUtf8("statsBarCheckBoxLabel"))
        self.horizontalLayout.addWidget(self.statsBarCheckBoxLabel)
        spacerItem1 = QtGui.QSpacerItem(30, 30, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.statsBarGameSpeedProgress = QtGui.QProgressBar(self.statsBarContainerWidget)
        self.statsBarGameSpeedProgress.setMinimumSize(QtCore.QSize(200, 30))
        self.statsBarGameSpeedProgress.setMaximumSize(QtCore.QSize(16777215, 30))
        self.statsBarGameSpeedProgress.setProperty("value", 0)
        self.statsBarGameSpeedProgress.setInvertedAppearance(False)
        self.statsBarGameSpeedProgress.setObjectName(_fromUtf8("statsBarGameSpeedProgress"))
        self.horizontalLayout.addWidget(self.statsBarGameSpeedProgress)
        self.statsBarSpeedLabel = QtGui.QLabel(self.statsBarContainerWidget)
        self.statsBarSpeedLabel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsBarSpeedLabel.sizePolicy().hasHeightForWidth())
        self.statsBarSpeedLabel.setSizePolicy(sizePolicy)
        self.statsBarSpeedLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.statsBarSpeedLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.statsBarSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statsBarSpeedLabel.setObjectName(_fromUtf8("statsBarSpeedLabel"))
        self.horizontalLayout.addWidget(self.statsBarSpeedLabel)
        spacerItem2 = QtGui.QSpacerItem(0, 30, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.statsBarLivesLabel = QtGui.QLabel(self.statsBarContainerWidget)
        self.statsBarLivesLabel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsBarLivesLabel.sizePolicy().hasHeightForWidth())
        self.statsBarLivesLabel.setSizePolicy(sizePolicy)
        self.statsBarLivesLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.statsBarLivesLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.statsBarLivesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statsBarLivesLabel.setObjectName(_fromUtf8("statsBarLivesLabel"))
        self.horizontalLayout.addWidget(self.statsBarLivesLabel)
        self.statsBarLivesValue = QtGui.QLCDNumber(self.statsBarContainerWidget)
        self.statsBarLivesValue.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsBarLivesValue.sizePolicy().hasHeightForWidth())
        self.statsBarLivesValue.setSizePolicy(sizePolicy)
        self.statsBarLivesValue.setMinimumSize(QtCore.QSize(50, 30))
        self.statsBarLivesValue.setMaximumSize(QtCore.QSize(50, 30))
        self.statsBarLivesValue.setSmallDecimalPoint(False)
        self.statsBarLivesValue.setNumDigits(1)
        self.statsBarLivesValue.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.statsBarLivesValue.setProperty("intValue", 0)
        self.statsBarLivesValue.setObjectName(_fromUtf8("statsBarLivesValue"))
        self.horizontalLayout.addWidget(self.statsBarLivesValue)
        self.statsBarScoreLabel = QtGui.QLabel(self.statsBarContainerWidget)
        self.statsBarScoreLabel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsBarScoreLabel.sizePolicy().hasHeightForWidth())
        self.statsBarScoreLabel.setSizePolicy(sizePolicy)
        self.statsBarScoreLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.statsBarScoreLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.statsBarScoreLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statsBarScoreLabel.setObjectName(_fromUtf8("statsBarScoreLabel"))
        self.horizontalLayout.addWidget(self.statsBarScoreLabel)
        self.statsBarScoreValue = QtGui.QLCDNumber(self.statsBarContainerWidget)
        self.statsBarScoreValue.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsBarScoreValue.sizePolicy().hasHeightForWidth())
        self.statsBarScoreValue.setSizePolicy(sizePolicy)
        self.statsBarScoreValue.setMinimumSize(QtCore.QSize(100, 30))
        self.statsBarScoreValue.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.statsBarScoreValue.setFont(font)
        self.statsBarScoreValue.setFrameShape(QtGui.QFrame.Box)
        self.statsBarScoreValue.setFrameShadow(QtGui.QFrame.Raised)
        self.statsBarScoreValue.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.statsBarScoreValue.setObjectName(_fromUtf8("statsBarScoreValue"))
        self.horizontalLayout.addWidget(self.statsBarScoreValue)
        self.gridLayout.addWidget(self.statsBarContainerWidget, 0, 0, 1, 1)
        self.citizenPacGraphicsView = QtGui.QGraphicsView(self.citizenCentralWidget)
        self.citizenPacGraphicsView.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.citizenPacGraphicsView.sizePolicy().hasHeightForWidth())
        self.citizenPacGraphicsView.setSizePolicy(sizePolicy)
        self.citizenPacGraphicsView.setMinimumSize(QtCore.QSize(0, 0))
        self.citizenPacGraphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.citizenPacGraphicsView.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.citizenPacGraphicsView.setForegroundBrush(brush)
        self.citizenPacGraphicsView.setObjectName(_fromUtf8("citizenPacGraphicsView"))
        self.gridLayout.addWidget(self.citizenPacGraphicsView, 1, 0, 1, 1)
        CitizenPacMainWindow.setCentralWidget(self.citizenCentralWidget)

        self.retranslateUi(CitizenPacMainWindow)
        QtCore.QMetaObject.connectSlotsByName(CitizenPacMainWindow)

    def retranslateUi(self, CitizenPacMainWindow):
        CitizenPacMainWindow.setWindowTitle(_translate("CitizenPacMainWindow", "CitizenPac", None))
        self.statsBarCheckBoxLabel.setText(_translate("CitizenPacMainWindow", "Game Running", None))
        self.statsBarSpeedLabel.setText(_translate("CitizenPacMainWindow", "Speed Boost", None))
        self.statsBarLivesLabel.setText(_translate("CitizenPacMainWindow", "Lives", None))
        self.statsBarScoreLabel.setText(_translate("CitizenPacMainWindow", "Score", None))

import citizen_pac_rc
